### ISSUE TITLE
Buyer cart

### ISSUE THREAD

**Issue by MrMelon1232** [MrMelon1232/group_L-soen341project2022#11]
As a user buyer, I should be able to add/review items in my cart because I need to gather all items before checking out.

Story Points: 13
Explanation: Cart implementation is one of our core features and is crucial to the success of the website, as without a cart, users will not be able to reserve items to checkout and purchase and it might create inventory conflict. 

- [x] #40 
- [x] #38 

Risk Assessment:
   - Items in the cart may link or refer to another item, hence providing the buyer with the wrong purchases.
   - Items may be sold out but still added in the buyer's cart.
   - Possible Counter Measures:
     - Having a review checkup with the user after adding all items to cart
     - Notifying the user that the item is sold out

**Comment by MrMelon1232** [comment]
Acceptance Test Suites

Test Suite 1:Front-End

- Test Case 1:
  Access cart via navbar
- Test Case 2:
  Review, manage and modify items in user cart

**Comment by NateTheL8** [comment]
Acceptance Test Suites

Test Suite 2: Back-End

-Test Case 1:
Authenticate user login 
-Test Case 2:
View all listings and their quantities in user cart
- Test Case 3: 
Modify listing quantity
- Test Case 4: 
Remove listing
- Test Case 5: 
Display correct total amount of user cart
