### ISSUE TITLE
login/signup form

### ISSUE THREAD

**Issue by MrMelon1232** [MrMelon1232/group_L-soen341project2022#24]
- [x] Prompt username and password
- [x] Forgot password option
- [x] Sign up/register option
- [x] prompt email, password, name and last name for signup
- [x] terms and conditions
- [x] email validator
- [x] Integrate in navbar

**Comment by MrMelon1232** [comment]
#38 refactoring code issue to be done as related to this issue.

**Comment by zeinebbenmami** [comment]
All tasks completed
