### ISSUE TITLE
Manage profile page

### ISSUE THREAD

**Issue by MrMelon1232** [MrMelon1232/group_L-soen341project2022#29]
As a user, I should be able to manage my profile page to add information or remove information on my existing account.

Story Points: 8 
Explanation: Users should be able to managing their profile so that they don't have to create a new profile any time their information change. This user story does not demand much effort since it is only giving permission to the users to edit their profiles on the website.

- [x] #24 
- [x] #38
- [x] Add shipping information
- [x] Add billing information
- [x] Add password change choice
- [x] Modification for information

**Comment by NateTheL8** [comment]
<img width="608" alt="Issue #29" src="https://user-images.githubusercontent.com/59817423/159202384-9acb1398-e842-41f8-a0e6-27af0e8b9cf7.png">
